import Link from 'next/link';
import { ClubJoinButton } from '@/components/network/club-join-button';
import { NetworkGate } from '@/components/network/network-gate';
import { Container, EmptyState } from '@/components/ui/primitives';
import { getCurrentUser } from '@/server/auth/session';
import { getNetworkStatuses, getPublicClubDiscovery } from '@/server/services/network';

export const dynamic='force-dynamic'; export const metadata={title:'Public clubs'};
export default async function PublicClubsPage(){const user=await getCurrentUser();const status=(await getNetworkStatuses()).find((row)=>row.key==='public_clubs')!;if(!status.available)return <Container className="py-10"><NetworkGate surface="public_clubs" metrics={status.metrics} streak={status.streak}/></Container>;const rows=await getPublicClubDiscovery(user?.id??null);return <Container size="wide" className="py-8 pb-20"><header><p className="eyebrow">Network · Movie Clubs</p><h1 className="mt-2 text-4xl">Active public clubs</h1><p className="mt-2 text-sm text-muted">Every listed club has at least three active members and two completed screenings in the last 180 days.</p></header>{rows.length?<ul className="mt-8 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(({club,recentScreenings})=><li key={club.id} className="flex min-h-48 flex-col rounded-lg border border-line p-4"><Link href={`/club/${club.slug}`} className="text-xl font-medium hover:text-iris">{club.name}</Link><p className="mt-1 text-xs text-dim">{club.memberCount} members · {recentScreenings} recent screenings</p><p className="mt-3 line-clamp-3 text-sm text-muted">{club.description??'A public Movie Club on Nitrate.'}</p><div className="mt-auto flex items-center justify-between gap-3 pt-4"><span className="text-xs text-dim">{club.joinPolicy.replaceAll('_',' ')}</span><ClubJoinButton clubId={club.id} policy={club.joinPolicy} signedIn={Boolean(user)}/></div></li>)}</ul>:<div className="mt-8"><EmptyState title="No active public clubs" description="Inactive or undersized clubs are omitted rather than padded into discovery."/></div>}</Container>}
