import Link from 'next/link';
import { ClubJoinButton } from '@/components/network/club-join-button';
import { redirect } from 'next/navigation';
import { Container, EmptyState } from '@/components/ui/primitives';
import { getCurrentUser } from '@/server/auth/session';
import { getNetworkStatuses, getPublicClubDiscovery } from '@/server/services/network';

export const dynamic='force-dynamic'; export const metadata={title:'Interesting Movie Clubs',robots:{index:false,follow:false}};
export default async function PublicClubsPage(){const user=await getCurrentUser();const status=(await getNetworkStatuses()).find((row)=>row.key==='public_clubs')!;if(!status.available)redirect('/network');const rows=await getPublicClubDiscovery(user?.id??null);return <Container size="wide" className="py-8 pb-20"><header><p className="eyebrow">Network · Movie Clubs</p><h1 className="mt-2 text-4xl">Interesting Movie Clubs</h1><p className="mt-2 text-sm text-muted">Public groups with an active film-watching rhythm.</p></header>{rows.length?<ul className="mt-8 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(({club,recentScreenings})=><li key={club.id} className="flex min-h-48 flex-col rounded-lg border border-line p-4"><Link href={`/club/${club.slug}`} className="text-xl font-medium hover:text-iris">{club.name}</Link><p className="mt-1 text-xs text-dim">{club.memberCount} members · {recentScreenings} recent screenings</p><p className="mt-3 line-clamp-3 text-sm text-muted">{club.description??'A public Movie Club on Nitrate.'}</p><div className="mt-auto flex items-center justify-between gap-3 pt-4"><span className="text-xs text-dim">{club.joinPolicy.replaceAll('_',' ')}</span><ClubJoinButton clubId={club.id} policy={club.joinPolicy} signedIn={Boolean(user)}/></div></li>)}</ul>:<div className="mt-8"><EmptyState title="No public clubs to feature yet" description="When a public club has a steady movie-night rhythm, it can appear here."/></div>}</Container>}
