import { Container, EmptyState } from '@/components/ui/primitives';
import { NetworkGate } from '@/components/network/network-gate';
import { FollowButton } from '@/components/user/follow-button';
import { recommendationReasonLabel } from '@/lib/recommendations';
import { confidenceLabel } from '@/lib/network';
import { requireUser } from '@/server/auth/session';
import { getNetworkPeople, getNetworkStatuses } from '@/server/services/network';

export const dynamic = 'force-dynamic'; export const metadata = { title: 'Network people' };
export default async function NetworkPeoplePage() { const user = await requireUser(); const status = (await getNetworkStatuses()).find((row) => row.key === 'people')!; if (!status.available) return <Container className="py-10"><NetworkGate surface="people" metrics={status.metrics} streak={status.streak} /></Container>; const people = await getNetworkPeople(user.id); return <Container size="wide" className="py-8 pb-20"><header className="max-w-2xl"><p className="eyebrow">Network · People</p><h1 className="mt-2 text-4xl">People with explainable overlap</h1><p className="mt-2 text-sm text-muted">A taste claim appears only with at least 10 shared ratings. Confidence labels describe evidence, never a match percentage.</p></header>{people.length ? <ul className="mt-8 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{people.map((item) => <li key={item.user.id} className="flex min-h-40 flex-col rounded-lg border border-line p-4"><a href={`/@${item.user.username}`} className="text-lg font-medium hover:text-ember">{item.user.displayName}</a><p className="text-xs text-dim">@{item.user.username} · {item.sharedRatings} shared ratings{confidenceLabel(item.sharedRatings) ? ` · ${confidenceLabel(item.sharedRatings)} confidence` : ''}</p><ul className="mt-3 space-y-1 text-xs text-muted">{item.reasons.slice(0,3).map((reason) => <li key={reason.kind}>{recommendationReasonLabel(reason)}</li>)}</ul><div className="mt-auto pt-4"><FollowButton userId={item.user.id} initialFollowing={false} signedIn source="network" /></div></li>)}</ul> : <div className="mt-8"><EmptyState title="No eligible people right now" description="Privacy, blocks, existing follows and the 10-rating evidence floor are applied before display." /></div>}</Container>; }
